(()=>{
const KEY='aither-backend-url',API=()=>localStorage.getItem(KEY)||'https://aither-backend.onrender.com';
const css=document.createElement('style');css.textContent=`#aitherAccount{position:fixed;right:16px;top:max(14px,env(safe-area-inset-top));z-index:80;border:1px solid #ffffff22;border-radius:999px;background:#202124e8;color:#fff;padding:9px 13px;font:700 12px system-ui;backdrop-filter:blur(16px);box-shadow:0 8px 30px #0005}.aither-account-modal{position:fixed;inset:0;z-index:100;display:grid;place-items:center;padding:16px;background:#0009;backdrop-filter:blur(7px)}.aither-account-card{width:min(430px,100%);border:1px solid #ffffff25;border-radius:20px;background:#202124;color:#fff;padding:22px;box-shadow:0 25px 80px #000}.aither-account-card h2{margin:0}.aither-account-form{display:grid;gap:10px;margin-top:18px}.aither-account-form input{width:100%;min-height:44px;border:1px solid #ffffff25;border-radius:10px;background:#303134;color:#fff;padding:9px 11px}.aither-account-form button,.aither-account-close{min-height:44px;border:0;border-radius:10px;background:#8ab4f8;color:#202124;font-weight:800}.aither-account-close{background:transparent;color:#fff;position:absolute;right:18px;top:15px;font-size:22px}.aither-account-switch{border:0;background:transparent;color:#8ab4f8;padding:10px}.aither-account-status{min-height:20px;color:#b8c1cc;font-size:12px;margin-top:10px}.aither-account-user{display:grid;gap:7px;margin:18px 0;padding:14px;border:1px solid #ffffff18;border-radius:13px;background:#303134}.aither-account-user small{color:#b8c1cc}.aither-account-logout{width:100%;min-height:44px;border:1px solid #ffffff25;border-radius:10px;background:#303134;color:#fff;font-weight:700}.aither-account-modal[hidden]{display:none!important}`;document.head.appendChild(css);
const b=document.createElement('button');b.id='aitherAccount';b.type='button';b.textContent='Aither Account';b.setAttribute('aria-label','Aither Account');document.body.appendChild(b);
const m=document.createElement('div');m.className='aither-account-modal';m.hidden=true;m.innerHTML=`<div class="aither-account-card"><button class="aither-account-close" type="button">×</button><div style="font-size:10px;letter-spacing:.16em;color:#8ab4f8;font-weight:900">AITHER ECOSYSTEM</div><h2 id="aitherAccountTitle">Aither Account</h2><div id="aitherAccountBody"></div></div>`;document.body.appendChild(m);const body=m.querySelector('#aitherAccountBody');let mode='login',user=null;
async function req(path,opt={}){const r=await fetch(API()+path,{...opt,credentials:'include',headers:{'Content-Type':'application/json',...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(Array.isArray(d.detail)?d.detail.map(x=>x.msg).join(', '):(d.detail||`Request failed (${r.status})`));return d}
function render(){if(user){body.innerHTML=`<div class="aither-account-user"><strong>${esc(user.name)}</strong><small>${esc(user.email)}</small><small>${user.email_verified?'Email verified':'Email not verified'}</small></div><button id="aitherLogout" class="aither-account-logout" type="button">Sign out</button>`;body.querySelector('#aitherLogout').onclick=logout;return}body.innerHTML=`<form class="aither-account-form" id="aitherAuthForm">${mode==='register'?'<input name="name" autocomplete="name" placeholder="Name" maxlength="80" required>':''}<input name="email" type="email" autocomplete="email" placeholder="Email" required><input name="password" type="password" autocomplete="${mode==='register'?'new-password':'current-password'}" minlength="8" placeholder="Password" required><button type="submit">${mode==='register'?'Create account':'Sign in'}</button></form><div id="aitherAccountStatus" class="aither-account-status"></div><button id="aitherSwitch" class="aither-account-switch" type="button">${mode==='register'?'Already have an account? Sign in':'Need an account? Create one'}</button>`;body.querySelector('form').onsubmit=submit;body.querySelector('#aitherSwitch').onclick=()=>{mode=mode==='login'?'register':'login';render()}}
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
async function submit(e){e.preventDefault();const f=e.currentTarget,s=body.querySelector('#aitherAccountStatus'),d=Object.fromEntries(new FormData(f));s.textContent='Connecting to Aither Backend…';try{const r=await req(mode==='register'?'/api/auth/register':'/api/auth/login',{method:'POST',body:JSON.stringify(d)});user=r.user;render();window.dispatchEvent(new CustomEvent('aither:user-changed',{detail:{user}}))}catch(e){s.textContent=e.message}}
async function session(){try{const r=await req('/api/auth/session');user=r.authenticated?r.user:null}catch{user=null}render();window.dispatchEvent(new CustomEvent('aither:user-changed',{detail:{user}}))}
async function logout(){try{await req('/api/auth/logout',{method:'POST'})}catch{}user=null;render();window.dispatchEvent(new CustomEvent('aither:user-changed',{detail:{user}}))}
b.onclick=()=>{m.hidden=false;session()};m.querySelector('.aither-account-close').onclick=()=>m.hidden=true;m.onclick=e=>{if(e.target===m)m.hidden=true};document.addEventListener('keydown',e=>{if(e.key==='Escape')m.hidden=true});render();session();
})();