const KEY='aither-notes-v1';let notes=JSON.parse(localStorage.getItem(KEY)||'[]');let current=null;let view='all',folder='All',query='',desc=true;
const $=id=>document.getElementById(id);const save=()=>localStorage.setItem(KEY,JSON.stringify(notes));
function format(d){return new Date(d).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function filtered(){return notes.filter(n=>(view==='all'||(view==='pinned'&&n.pinned)||(view==='favorites'&&n.favorite))&&(folder==='All'||n.folder===folder)&&(!query||(n.title+' '+n.body).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>desc?b.updated-a.updated:a.updated-b.updated)}
function render(){let list=filtered();$('notes').innerHTML=list.map(n=>`<article class="card" onclick="editNote('${n.id}')"><div class="card-top"><h3>${esc(n.title||'Untitled note')}</h3><span>${n.pinned?'📌':n.favorite?'⭐':''}</span></div><p>${esc(n.body||'Empty note')}</p><div class="meta"><span class="tag">${esc(n.folder)}</span><span>${format(n.updated)}</span></div></article>`).join('');$('empty').classList.toggle('hidden',list.length>0);$('notes').classList.toggle('hidden',!list.length);$('allCount').textContent=notes.length;$('pinnedCount').textContent=notes.filter(n=>n.pinned).length;$('favoriteCount').textContent=notes.filter(n=>n.favorite).length;$('title').textContent=view==='pinned'?'Pinned':view==='favorites'?'Favorites':folder==='All'?'All notes':folder;$('viewLabel').textContent=view==='all'?'YOUR NOTES':view.toUpperCase();}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function newNote(){let n={id:crypto.randomUUID(),title:'',body:'',folder:folder==='All'?'Personal':folder,pinned:false,favorite:false,updated:Date.now()};notes.unshift(n);save();editNote(n.id)}
function editNote(id){current=notes.find(n=>n.id===id);if(!current)return;$('noteTitle').value=current.title;$('noteBody').value=current.body;$('noteFolder').value=current.folder;$('pin').textContent=current.pinned?'📍':'📌';$('favorite').textContent=current.favorite?'★':'☆';$('editor').classList.remove('hidden');$('noteTitle').focus()}
function close(){if(!current)return;$('editor').classList.add('hidden');current=null;render()}
function update(){if(!current)return;current.title=$('noteTitle').value;current.body=$('noteBody').value;current.folder=$('noteFolder').value;current.updated=Date.now();save();$('saveStatus').textContent='Saved locally'}
$('newNote').onclick=newNote;$('emptyNew').onclick=newNote;$('closeEditor').onclick=close;$('noteTitle').oninput=update;$('noteBody').oninput=update;$('noteFolder').onchange=update;$('pin').onclick=()=>{current.pinned=!current.pinned;update();editNote(current.id)};$('favorite').onclick=()=>{current.favorite=!current.favorite;update();editNote(current.id)};$('delete').onclick=()=>{if(confirm('Delete this note?')){notes=notes.filter(n=>n.id!==current.id);save();close()}};
$('search').oninput=e=>{query=e.target.value;render()};$('sort').onclick=()=>{desc=!desc;$('sort').textContent=desc?'Updated ↓':'Updated ↑';render()};$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('aither-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('aither-theme')==='dark')document.body.classList.add('dark');
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;folder='All';document.querySelectorAll('.folder').forEach(x=>x.classList.remove('active'));render()});document.querySelectorAll('.folder').forEach(b=>b.onclick=()=>{document.querySelectorAll('.folder').forEach(x=>x.classList.remove('active'));b.classList.add('active');folder=b.dataset.folder;view='all';document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelector('.nav[data-view="all"]').classList.add('active');render()});$('addFolder').onclick=()=>alert('Folders are built in for now: Personal, School, and Ideas.');document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('search').focus()}if(e.key==='Escape'&&!$('editor').classList.contains('hidden'))close()});render();
