const KEY='aither-notes-v3';
let notes=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('aither-notes-v2')||localStorage.getItem('aither-notes-v1')||'[]');
let current=null,view='all',folder='All',query='',desc=true;
const $=id=>document.getElementById(id); const save=()=>localStorage.setItem(KEY,JSON.stringify(notes));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const format=d=>new Date(d).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
function filtered(){return notes.filter(n=>(view==='all'||(view==='pinned'&&n.pinned)||(view==='favorites'&&n.favorite))&&(folder==='All'||n.folder===folder)&&(!query||(n.title+' '+n.body).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>desc?b.updated-a.updated:a.updated-b.updated)}
function render(){const list=filtered();$('notes').innerHTML=list.map(n=>`<article class="card" data-id="${n.id}"><div class="card-top"><h3>${esc(n.title||'Untitled note')}</h3><span class="status">${n.pinned?'Pinned':n.favorite?'Favorite':''}</span></div><p>${esc(n.body||'Empty note')}</p><div class="meta"><span class="tag">${esc(n.folder||'Personal')}</span><span>${format(n.updated)}</span></div></article>`).join('');$('empty').classList.toggle('hidden',list.length>0);$('notes').classList.toggle('hidden',!list.length);$('allCount').textContent=notes.length;$('pinnedCount').textContent=notes.filter(n=>n.pinned).length;$('favoriteCount').textContent=notes.filter(n=>n.favorite).length;$('title').textContent=view==='pinned'?'Pinned':view==='favorites'?'Favorites':folder==='All'?'All notes':folder;$('viewLabel').textContent=view==='all'?'YOUR NOTES':view.toUpperCase()}
function newNote(){const n={id:crypto.randomUUID(),title:'',body:'',folder:folder==='All'?'Personal':folder,pinned:false,favorite:false,updated:Date.now()};notes.unshift(n);save();editNote(n.id)}
function editNote(id){current=notes.find(n=>n.id===id);if(!current)return;$('noteTitle').value=current.title;$('noteBody').value=current.body;$('noteFolder').value=['Personal','School','Ideas'].includes(current.folder)?current.folder:'Personal';$('pin').textContent=current.pinned?'Unpin':'Pin';$('favorite').textContent=current.favorite?'Unfavorite':'Favorite';$('editor').classList.remove('hidden');document.body.classList.add('editing');setTimeout(()=>$('noteTitle').focus(),50)}
function close(){if(!current)return;update();$('editor').classList.add('hidden');document.body.classList.remove('editing');current=null;render()}
function update(){if(!current)return;current.title=$('noteTitle').value;current.body=$('noteBody').value;current.folder=$('noteFolder').value;current.updated=Date.now();save();$('saveStatus').textContent='Saved'}
$('newNote').onclick=newNote;$('emptyNew').onclick=newNote;$('mobileNew').onclick=newNote;$('closeEditor').onclick=close;$('noteTitle').oninput=update;$('noteBody').oninput=update;$('noteFolder').onchange=update;
$('pin').onclick=()=>{current.pinned=!current.pinned;update();editNote(current.id)};$('favorite').onclick=()=>{current.favorite=!current.favorite;update();editNote(current.id)};
$('delete').onclick=()=>{if(confirm('Delete this note?')){notes=notes.filter(n=>n.id!==current.id);save();close()}};
$('search').oninput=e=>{query=e.target.value;render()};$('sort').onclick=()=>{desc=!desc;$('sort').textContent=desc?'Updated ↓':'Updated ↑';render()};
$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('aither-theme',document.body.classList.contains('dark')?'dark':'light');$('theme').textContent=document.body.classList.contains('dark')?'Light':'Dark'};
if(localStorage.getItem('aither-theme')==='dark'){document.body.classList.add('dark');$('theme').textContent='Light'}
function setView(v){view=v;folder='All';document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.querySelectorAll('.folder').forEach(x=>x.classList.remove('active'));render()}
document.querySelectorAll('.nav,.mobile-nav-btn[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
document.querySelectorAll('.folder').forEach(b=>b.onclick=()=>{folder=b.dataset.folder;view='all';document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view==='all'));document.querySelectorAll('.folder').forEach(x=>x.classList.toggle('active',x===b));render()});
$('notes').addEventListener('click',e=>{const card=e.target.closest('.card');if(card)editNote(card.dataset.id)});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('search').focus()}if(e.key==='Escape'&&!$('editor').classList.contains('hidden'))close()});
let touchStart=0;document.addEventListener('touchstart',e=>touchStart=e.changedTouches[0].screenX,{passive:true});document.addEventListener('touchend',e=>{if(!document.body.classList.contains('editing'))return;const dx=e.changedTouches[0].screenX-touchStart;if(dx>90)close()},{passive:true});
render();